apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-node.secretname" . }}
stringData:
  {{- if .Values.rollupConfig.file }}
  {{ .Values.rollupConfig.filename }}: {{ .Values.rollupConfig.file }}
  {{- end }}

  {{- if .Values.p2p.priv.file }}
  {{ .Values.p2p.priv.filename }}: {{ .Values.p2p.priv.file }}
  {{- end }}
