apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.op.ports }}
    {{- if or $value.enabled (eq $key "rpc") }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
    {{- end }}
    {{- end }}
    - name: tcp-p2p
      port: {{ index .Values.op.ports.p2p "listen.tcp" }}
      targetPort: tcp-p2p
      {{- if and (ne .Values.service.type "ClusterIP") .Values.service.p2pNodePortTCP }}
      nodePort: {{ .Values.service.p2pNodePortTCP }}
      {{- end }}
    - name: udp-p2p
      port: {{ index .Values.op.ports.p2p "listen.udp" }}
      targetPort: udp-p2p
      {{- if and (ne .Values.service.type "ClusterIP") .Values.service.p2pNodePortUDP }}
      nodePort: {{ .Values.service.p2pNodePortUDP }}
      {{- end }}

  selector:
    {{- include "op-node.selectorLabels" . | nindent 4 }}
