apiVersion: v1
kind: Service
metadata:
  name: {{ include "l2geth.fullname" . }}
  labels:
    {{- include "l2geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.l2geth.ports }}
    {{- if $value.enabled }}
    - name: {{ $key }}
      port: {{ if eq $key "metrics" }}8686{{ end }}{{ $value.port }}
      targetPort: {{ $key }}
    {{- end }}
    {{- end }}
    {{- if .Values.l2geth.env.RPC_ENABLE }}
    - name: rpc
      port: {{ .Values.l2geth.env.RPC_PORT }}
      targetPort: rpc
    {{- end }}
    - name: p2p
      port: {{ .Values.l2geth.ports.p2p.port }}
      targetPort: p2p
      {{- if and (ne .Values.service.type "ClusterIP") .Values.service.p2pNodePort }}
      nodePort: {{ .Values.service.p2pNodePort }}
      {{- end }}
  selector:
    {{- include "l2geth.selectorLabels" . | nindent 4 }}
