# Default values are set for Optimism Goerli Testnet.

replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe: true
readinessProbe: true

#######################################
# op-node settings as args
#######################################
network: op-mainnet

l1:
  rpcAddr: # place your eth mainnet execution client's RPC address including https:// or wss://"
  beacon: # place your eth mainnet execution client's RPC address including https:// or wss://"

l2:
  rpcAddr: # place your execution client's RPC address including https:// or wss://
  # best practice suggest to create your own secret and indicate only the secret name and key to avoid having it in plain text
  # if you still want create the secret with the chart, mention the jwt in the value field
  jwtSecret:
    secretName: authrpc-jwt
    key: jwt
    # replace 'false' by your jwt to create the secret with your chart
    value: false

rpc:
  port:
    name: rpc-port
    containerPort: 8545
    hostPort: 7545
  addr: 0.0.0.0
  enableAdmin: false

snapshotLogPath: /logs

rollupConfig:
  file:
  filename: rollup.json

sequencer:
  enabled: false
  p2pKey:

p2p:
  enabled: true
  listen:
    ip: 0.0.0.0
    tcp:
      name: p2p-tcp-port
      containerPort: 9003
      hostPort: 9003
    udp:
      name: p2p-udp-port
      containerPort: 9003
      hostPort: 9003
  priv:
    file:
    filename: p2ppriv.txt  # file path to store p2p.priv

metrics:
  enabled: true
  addr: 0.0.0.0
  port:
    name: metrics-port
    containerPort: 7300
    hostPort: 7300

pprof:
  enabled: true
  addr: 0.0.0.0
  port:
    name: pprof-port
    containerPort: 6060
    hostPort: 6060

# rest application arguments
extraArgs: []

secretForVolumeMountDir: /secrets