apiVersion: v1
kind: Secret
metadata:
  name: {{ include "erigon.secretname" . }}
stringData:
  {{- if .Values.authrpc.jwtSecret.file }}
  {{ .Values.authrpc.jwtSecret.filename }}: {{ .Values.authrpc.jwtSecret.file }}
  {{- end }}
