apiVersion: v1
kind: Service
metadata:
  name: {{ include "erigon.fullname" . }}
  labels:
    {{- include "erigon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.erigon.ports }}
    {{- if or $value.enabled (eq $key "authrpc") }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "erigon.selectorLabels" . | nindent 4 }}
