apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # HTTP RPC
    {{- if .Values.geth.http.enabled }}
    - name: http-rpc
      port: {{ .Values.geth.http.port }}
      targetPort: {{ .Values.geth.http.port }}
    {{- end }}
    # WS RPC
    {{- if .Values.geth.ws.enabled }}
    - name: ws-rpc
      port: {{ .Values.geth.ws.port }}
      targetPort: {{ .Values.geth.ws.port }}
    {{- end }}
    # AuthRPC
    {{- if .Values.geth.authrpc.enabled }}
    - name: auth-rpc
      port: {{ .Values.geth.authrpc.port }}
      targetPort: {{ .Values.geth.authrpc.port }}
    {{- end }}
    # Metrics
    {{- if .Values.geth.metrics.enabled }}
    - name: metrics
      port: {{ .Values.geth.metrics.port }}
      targetPort: {{ .Values.geth.metrics.port }}
    {{- end }}
    # pprof
    {{- if .Values.geth.pprof.enabled }}
    - name: pprof
      port: {{ .Values.geth.pprof.port }}
      targetPort: {{ .Values.geth.pprof.port }}
    {{- end }}
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
