apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "geth.name" . }}
  selector:
    matchLabels:
      {{- include "geth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geth.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: preprocess
        command: ["/bin/sh", "-c"]
        args:
          - |
            rm -rf /data{{ .Values.geth.datadir }}/geth/LOCK  # remove lock
            rm -rf /data{{ .Values.geth.datadir }}/geth/nodekey  # remove nodekey
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data
      {{- if .Values.importTarURL }}
      - name: import-chain
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ -f "/data/imported" ]; then
            echo "already imported"
            ls /root/data
            else
            echo "Chain import start"
            wget -O /data/imported.tar {{ .Values.importTarURL }}  # download from URL
            rm -rf /data{{ .Values.geth.datadir }}  # clean dir
            mkdir -p /data{{ .Values.geth.datadir }}
            tar -xf /data/imported.tar -C /data{{ .Values.geth.datadir }}/
            rm -rf /data/imported.tar
            touch /data/imported
            ls /data{{ .Values.geth.datadir }}
            echo "Chain import finished"
            fi
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data
      {{- end }}
      containers:
        - name: {{ template "geth.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            # HTTP RPC
            {{- if .Values.geth.http.enabled }}
            - name: http-rpc
              containerPort: {{ .Values.geth.http.port }}
            {{- end }}
            # WS RPC
            {{- if .Values.geth.ws.enabled }}
            - name: ws-rpc
              containerPort: {{ .Values.geth.ws.port }}
            {{- end }}
            # AuthRPC
            {{- if .Values.geth.authrpc.enabled }}
            - name: auth-rpc
              containerPort: {{ .Values.geth.authrpc.port }}
            {{- end }}
            # Metrics
            {{- if .Values.geth.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.geth.metrics.port }}
            {{- end }}
            # pprof
            {{- if .Values.geth.pprof.enabled }}
            - name: pprof
              containerPort: {{ .Values.geth.pprof.port }}
            {{- end }}
          command: ["/usr/local/bin/geth"]
          args:
            - --op-network={{ .Values.geth.network }}
            - --datadir={{ .Values.geth.datadir }}
            - --syncmode={{.Values.syncMode}}

            # HTTP RPC
            {{- if .Values.geth.http.enabled }}
            - --http
            - --http.addr={{ .Values.geth.http.addr }}
            - --http.port={{ .Values.geth.http.port }}
            - --http.vhosts={{ .Values.geth.http.vhosts }}
            - --http.corsdomain={{ .Values.geth.http.corsDomain }}
            {{- end }}

            # WS RPC
            {{- if .Values.geth.ws.enabled }}
            - --ws
            - --ws.addr={{ .Values.geth.ws.addr }}
            - --ws.port={{.Values.geth.ws.port }}
            - --ws.origins={{.Values.geth.ws.origins}}
            {{- end }}

            # Auth RPC
            {{- if .Values.geth.authrpc.enabled }}
            - --authrpc.addr={{ .Values.authrpc.addr }}
            - --authrpc.port={{ .Values.authrpc.port }}
            - --authrpc.vhosts={{.Values.authrpc.vhosts}}
            - --authrpc.jwtsecret=/jwt/{{ .Values.geth.jwt.existingSecret.key | default jwtSecret }}
            {{- end }}

            # pprof
            {{- if .Values.geth.pprof.enabled }}
            - --pprof
            - --pprof.addr={{ .Values.geth.pprof.addr }}
            - --pprof.port={{ .Values.geth.pprof.port }}
            {{- end }}

            # metrics
            {{- if .Values.geth.metrics.enabled }}
            - --metrics
            - --metrics.addr={{ .Values.geth.metrics.addr }}
            - --metrics.port={{ .Values.geth.metrics.port }}
            {{- end }}

            # GC archive mode is required when we import the chain. Otherwise, imported data will be removed.
            {{- if .Values.importTarURL }}
            - --gcmode=archive
            {{- end }}

            # Other Arguments
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if and .Values.livenessProbe .Values.geth.http.enabled }}
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: http-rpc
          {{- end }}
          {{- if and .Values.readinessProbe .Values.geth.http.enabled }}
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: http-rpc
          {{- end }}
          volumeMounts:
          - name: data
            mountPath: /data
          - name: jwt
            mountPath: /jwt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: jwt
          secret:
            secretName: {{ .Values.geth.existingSecret.name | default jwtSecret }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.volumeClaimSpec }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        "helm.sh/resource-policy": keep
      labels:
        {{- include "geth.selectorLabels" . | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml .accessModes | nindent 8 }}
      resources:
        {{- toYaml .resources | nindent 8 }}
